export const supabaseUrl = 'https://aeaiexxpjztpdcqdvlfb.supabase.co'
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlYWlleHhwanp0cGRjcWR2bGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1NTg2NTAsImV4cCI6MjA0OTEzNDY1MH0.I0UI2CqaY0uaFQvL2brUSZsNh6JdCcnAz8Q3RKJ5qVs'
